project:
  type: website

website:
  title: "IS415 - Kendrick"
  # reader-mode: true
  # bread-crumbs: true
  navbar:
    search: true
    left:
      - text: "About"
        href: "about.html"
      - text: "In-Class Exercises"
        menu:
          - text: "CE1: Geospatial Data Science"
            href: "InClass/ICE1/in-class-1.html"
          - text: "CE2: Working with Master Plan Planning Subzone Data"
            href: "InClass/ICE2/in-class-2.html"
          - text: "CE3: Spatial Point Pattern Analysis"
            href: "InClass/ICE3/in-class-3.html"
          - text: "CE4/HX4: SPatial-Temporal Point Pattern Analysis"
            href: "InClass/ICE4/in-class-4.html"
          - text: "CE5: Spatial Weights and Applications"
            href: "InClass/ICE5/in-class-5.html"
          - text: "CE6: Measures of Spatial Autocorrelation"
            href: "InClass/ICE5/in-class-6.html"
          - text: "CE7: Geographical Segmentation with Spatially Constrained Clustering Techniques"
            href: "InClass/ICE7/in-class-7.html"
      #   menu:
      #   - href: "InClass/ICE1/in-class-1.qmd"
      #   - href: "InClass/ICE2/in-class-2.qmd"
      #   - href: "InClass/ICE3/in-class-3.qmd"
      #   - href: "InClass/ICE4/in-class-4.qmd"
      #   - href: "InClass/ICE5/in-class-5.qmd"
      #   - href: "InClass/ICE5/in-class-6.qmd"
      - text: "Hands-On Exercises"
        menu:
          - text: "HX1: Geospatial Data Wrangling with R"
            href: "HandsOn/Hands-on_Ex01/hands-on-1.html"
          - text: "HX2: Thematic Mapping and Geovisualisation with R"
            href: "HandsOn/Hands-on_Ex02/hands-on-2.html"
          - text: "HX3: Spatial Point Pattern Analysis"
            href: "HandsOn/Hands-on_Ex03/hands-on-3.html"
          - text: "HX4/CE4: SPatial-Temporal Point Pattern Analysis"
            href: "InClass/ICE4/in-class-4.html"
          - text: "HX5: Spatial Weights and Applications"
            href: "HandsOn/Hands-on_Ex05/hands-on-5.html"
          - text: "HX6: Methods of Spatial Autocorrelation"
            href: "HandsOn/hands-on-6.html"
          - text: "HX7: Geographical Segmentation with Spatially Constrained Clustering Techniques"
            href: "HandsOn/hands-on-7.html"
      #   - href: "HandsOn/Hands-on_Ex01/hands-on-1.qmd"
      #   - href: "HandsOn/Hands-on_Ex02/hands-on-2.qmd"
      #   # - text: "Hands-on Exercise 1"
      #   # - href: "HandsOn/Hands-on_Ex01/hands-on-1.html"
      #   # - text: "Hands-on Exercise 2"
      #   # - href: "HandsOn/Hands-on_Ex02/hands-on-2.html"
      #   - href: "HandsOn/Hands-on_Ex03/hands-on-3.qmd"
      #   - href: "InClass/ICE4/in-class-4.qmd"
      #   - href: "HandsOn/Hands-on_Ex05/hands-on-5.qmd"
      #   - href: "HandsOn/hands-on-6.qmd"
      #   - href: "HandsOn/hands-on-7.qmd"
      - text: "Take-home Exercises"
        menu:
          - text: "TH1: The Myanmar Civil War"
            href: "TakeHome/TakeHome1/take-home-1.html"
          - text: "TH2: Drug Abuse in Thailand"
            href: "TakeHome/TakeHome2/take-home-2.html"
        # - href: "TakeHome/TakeHome1/take-home-1.qmd"
        # - href: "TakeHome/TakeHome2/take-home-2.qmd"
  # sidebar:
  #   style: "floating"
  #   contents:
  #     - section: "Hands-on Exercises"
  #       contents:
  #         - text: "HX1: Geospatial Data Wrangling with R"
  #           href: "HandsOn/Hands-on_Ex01/hands-on-1.html"
  #         - text: "HX2: Thematic Mapping and Geovisualisation with R"
  #           href: "HandsOn/Hands-on_Ex02/hands-on-2.html"
  #         - text: "HX3: Spatial Point Pattern Analysis"
  #           href: "HandsOn/Hands-on_Ex03/hands-on-3.html"
  #         - text: "HX4/CE4: SPatial-Temporal Point Pattern Analysis"
  #           href: "InClass/ICE4/in-class-4.html"
  #         - text: "HX5: Spatial Weights and Applications"
  #           href: "HandsOn/Hands-on_Ex05/hands-on-5.html"
  #         - text: "HX6: Methods of Spatial Autocorrelation"
  #           href: "HandsOn/hands-on-6.html"
  #         - text: "HX7: Geographical Segmentation with Spatially Constrained Clustering Techniques"
  #           href: "HandsOn/hands-on-7.html"
  #     - section: "In-Class Exercises"
  #       contents:
  #         - text: "CE1: Geospatial Data Science"
  #           href: "InClass/ICE1/in-class-1.html"
  #         - text: "CE2: Geospatial Data Wrangling with R"
  #           href: "InClass/ICE2/in-class-2.html"
  #         - text: "CE3: Spatial Point Pattern Analysis"
  #           href: "InClass/ICE3/in-class-3.html"
  #         - text: "CE4/HX4: SPatial-Temporal Point Pattern Analysis"
  #           href: "InClass/ICE4/in-class-4.html"
  #         - text: "CE5: Spatial Weights and Applications"
  #           href: "InClass/ICE5/in-class-5.html"
  #         - text: "CE6: Methods of Spatial Autocorrelation"
  #           href: "InClass/ICE5/in-class-6.html"
  #         - text: "CE7: Geographical Segmentation with Spatially Constrained Clustering Techniques"
  #           href: "InClass/ICE7/in-class-7.html"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source