project:
  type: website

website:
  title: "IS415 Geospatial Analytics and Applications"
  navbar:
    left:
      - about.qmd
      - text: "In-Class Exercises"
        menu:
        - text: "To be updated"
      - text: "Hands-On Exercises"
        menu:
        - href: "Hands-on_Ex01/hands-on-1.qmd"
      - text: "Take-home Exercises"
        menu:
        - text: "To be updated" 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

